name: react
services:
  dashboard:
    container_name: dashboard-app
    restart: on-failure
    develop:
      watch:
        - action: sync
          path: .
          target: /dashboard
        - action: rebuild
          path: package.json
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - REACT_APP_GRAPHQL_URI=http://localhost:8097/graphql
    ports:
      - 3000:3000


