name: react-app
services:
  dashboard:
    container_name: dashboard
    restart: on-failure
    develop:
      watch:
        - action: sync
          path: .
          target: /dashboard
        - action: rebuild
          path: package.json
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000


