# docker-compose.yml

version: '3.7'

services:
  dashboard:
    container_name: dashboard
    image: riyadennis/dashboard:latest
    environment:
      - NODE_ENV=production
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - .:/dashboard
    networks:
      - backend
  identity-server:
    container_name: identity-server
    image: riyadennis/identity-server:latest
    volumes:
      - code_volume:/identity-server
    ports:
      - 8081:8081
    restart: on-failure
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes:
  init: {}
  code_volume: {}


